name: example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  pivox:
    path: ../
  http: ^1.1.0
  dio: ^5.3.2
  shared_preferences: ^2.2.0
  google_fonts: ^6.1.0
  ionicons: ^0.2.2
  get_it: ^8.0.3
  provider: ^6.1.1
  data_cache_x: ^0.1.5
  html: ^0.15.5+1
  fl_chart: ^0.65.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
